# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b1776d32ee112f9bf8b437c47e32c0f3d1053af1400c94af180266cab192fab68199498bba242616ad43467a58a1f8598952615ed93458cdb310d6855caef314

test:
  secret_key_base: e12f67bfd41acc2330d56a18da3c9fd90a0ce8f0f5fab27e2c2007d509c23cf7c126bc7289c4d391c139148a40be6a78ed7168daad620de8242de248098ad2da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
